### ISSUE TITLE
Make byu-header handle h1-6 tags in the site-title slot

### ISSUE THREAD

**Issue by ThatJoeMoore** [byuweb/byu-theme-components#154]
# One-Line Summary

Currently, header tags don't get styled properly when used as a site-title. See #153 

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

All

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [x] A request for a new feature/enhancement?

# Browsers Affected

All

# Web Site Platform

All

# Detailed Description

*Tell us all about your problem or feature proposal.*

**Comment by smoosh911** [comment]
h2, h4 ,h5 and h6 all work fine. It's just h1 and h3 that are being affected by styles in site.scss that make them color: $navy.

**Comment by kebowdog** [comment]
Not quite - what I think we need to do is also override the font-size, font-weight, etc. so that h1-h6 tags that use the site-title slot all look the same as a span or div tag using the site-title slot.

**Comment by rburkey87** [comment]
I've actually been looking at this. There's a lot of styling in site.scss that's overriding the existing styling in the components, even when the component's styling is more specific or marked important. It seems to affect HTML-built sites the most, since the Drupal and WordPress themes override (but ideally we're not hard-coding it there either). Unless it's something you want to handle specifically, I was going to clear out the styling from the site.scss file and make sure it's implemented elsewhere. It should fix a lot of issues with site-title (and it fixes the footer font from issue #144 too).

**Comment by kebowdog** [comment]
Rebecca, we already put in a PR for this (#161). It's been sitting for some time now so it might have merge errors, but it did basically what you're suggesting - ripped out the H1-H6 styles in site.css.
