### ISSUE TITLE
SEARCH on mobile should be aligned with B in BYU

### ISSUE THREAD

**Issue by Aleniras** [byuweb/byu-theme-components#227]
![image](https://cloud.githubusercontent.com/assets/26605197/26744798/b5c250da-47a4-11e7-9179-fdc5e395cf59.png)

**Comment by Aleniras** [comment]
Right now, it sits out to the left, and gets worse the smaller the device.

**Comment by Aleniras** [comment]
Please also center the search icon vertically.

**Comment by kebowdog** [comment]
@Aleniras I have a PR ready for aligning the placeholder text with the B in BYU. Regarding the search icon, it's already centered vertically, but the problem is that the icon has an even-numbered height (20 pixels) and the search bar has an odd-numbered height so it appears one pixel off from the vertical center axis:

![image](https://user-images.githubusercontent.com/19493582/27137876-482732fc-50dc-11e7-873c-0721da5122a5.png)

If I change the height of the search icon to 19px it looks more centered:

![image](https://user-images.githubusercontent.com/19493582/27137901-5abad4e6-50dc-11e7-8369-d5b56a0fd3d9.png)

The non-mobile view has the same problem in reverse, it's just not as noticeable:

Normal (17x17px search icon inside a 30px container):

![image](https://user-images.githubusercontent.com/19493582/27137983-9b3a3430-50dc-11e7-8bf2-9dc684c7feb7.png)

Modified (17x16px search icon inside a 30px container):

![image](https://user-images.githubusercontent.com/19493582/27138017-bbbf3980-50dc-11e7-8cf8-66b5ce171d22.png)

It's a subtle difference, but I think reducing the height by 1px in each case looks a little better. What are your thoughts?
