### ISSUE TITLE
byu-theme-components.js breaks bootstrap dropdown menus

### ISSUE THREAD

**Issue by WorldsEndless** [byuweb/byu-theme-components#347]
Vanilla bootstrap dropdown menus (https://getbootstrap.com/docs/3.3/components/#dropdowns) cease working if byu-theme-components.js is sourced. Clicking on what was a menu does nothing after sourcing the byu js.

**Comment by blakemorgan** [comment]
Can you please fill out the issue form below so we have more issue and can troubleshoot this? 

# Description

*Tell us all about your problem or feature proposal.*

**If the issue is with styling, please include screenshots!**



# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Safari for iOS
- [ ] Chrome for iOS
- [ ] Firefox Mobile for Safari
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by ThatJoeMoore** [comment]
I've reproduced the issue in chrome and am investigating the cause.

**Comment by ThatJoeMoore** [comment]
Hmm...once I remembered to include jQuery, my reproduction of the issue starting working properly. @WorldsEndless , could you post the console output from your browser devtools? Also, could you give us more details about how you're using the dropdown? For example, is it in the main body of the page, or are you using it in the nav menu?

**Comment by ThatJoeMoore** [comment]
I have good news and bad news:  I know what's happening, but we can't to change it.

Everything in the nav bar gets an `overflow: hidden!important` style set, which is why you don't see the dropdown menu appear.  It is appearing, it's just in the overflow space, and thus isn't being displayed.

That style is there, and we can't change it for now, because the current theme specification specifically forbids dropdown menus in the nav bar, with the exception of the 'More' menu that gets added if you have more than 6 nav items.

**Comment by WorldsEndless** [comment]
Ah; so clearly I shouldn't be trying to apply the theme with a web app (as opposed to a web site).

**Comment by ThatJoeMoore** [comment]
No, the theme is universal - everybody will be required to implement it next year for everything. You have to re-design your navigation.  This is easily the most controversial part of the new theme, but, unfortunately, it isn't changing anytime soon.
