### ISSUE TITLE
Custom dropdown menus

### ISSUE THREAD

**Issue by statman9** [byuweb/byu-theme-components#356]
# Description

*Tell us all about your problem or feature proposal.*
There should be a feature where there can be custom dropdown menus instead of just the "More" dropdown menu item that appears when there are more than 6 menu items. For example I can have 6 top-level menu items, but 3 of them display as custom dropdown menus (i.e. Link 1 (Link), Link 2 (Dropdown menu with "Link 7" and "Link 8"), Link 3 (Dropdown menu with "Link 9" and "Link 10"), Link 4 (Link), Link 5 (Dropdown with "Link 10" and "Link 11"), and Link 6 (Link)).

**If the issue is with styling, please include screenshots!**

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [x] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [x] Microsoft Edge
- [x] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [x] Safari for iOS
- [x] Chrome for iOS
- [x] Firefox Mobile for Safari
- [x]  Chrome for Android
- [x] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by kebowdog** [comment]
@statman9 Thanks for submitting an issue. This request comes up periodically since the lack of dropdowns is the biggest change most sites end up facing when adopting the new brand guidelines. It's mentioned briefly on the brand site (https://brand.byu.edu/guidelines/web/) but the decision not to allow dropdowns was a conscious, deliberate decision made by the web community design group. You can get more info on the research behind the decision by talking to the design group on the byu-web slack group.

Since taking dropdowns out of the menu requires a big adjustment in how you present your content, University Communications has hired a student to work with different departments to help them structure their content in a way that works with the new menu and still makes sense for the user. If you're interested you can contact @hadfieldjoe (joseph_hadfield@byu.edu) and he can help you with that. We've gone through this process for all of our department websites in the College of Life Sciences, and while it took some extra work at first we've been really happy with the end results and how much simpler it's made our site navigation.

I hope that makes sense. I'm going to close this issue as off-spec, but if you're having specific issues getting your content to work with the new menu I'd strongly recommend reaching out to Joe, Aleni, and/or the design group channel on slack.

**Comment by hadfieldjoe** [comment]
What site are you working with, @statman9 ? 

As Kevin mentioned, we've discussed this very issue extensively over the last two years. Our experience with previous BYU web themes has been that drop-down menus have been over-used greatly and tend to take the focus away from users' top tasks. Let's do a content review of your site and add this use case to the discussion.

**Comment by hadfieldjoe** [comment]
For department pages, take a look at the departments within Life Sciences. My team would also be happy to help review site content and plan the reorganization. 

Lab websites won't be required to use the BYU web theme, FYI.
