### ISSUE TITLE
[byu-header] Fallback Style Jitter with Action Buttons

### ISSUE THREAD

**Issue by ThatJoeMoore** [byuweb/byu-theme-components#413]
# Description

When using just an action button and nothing else, there's a lot of jitter when the page loads because the fallback styles place the button in the wrong location:

**Fallback Style**
![fallback-bad](https://user-images.githubusercontent.com/455981/46982716-aebd9080-d09a-11e8-9066-1fdd38d4689c.png)

**Full Components**
![fallback-good](https://user-images.githubusercontent.com/455981/46982718-b1b88100-d09a-11e8-99e6-c9fc43e78000.png)

This is probably a low-priority issue.

# Websites Affected

https://byu-oit.github.io/kotlin-uapi/

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

- [x] All

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by rburkey87** [comment]
@ThatJoeMoore - are you using any header attributes?

**Comment by rburkey87** [comment]
When creating the fallback styles, I couldn't get it to display correctly in constrained-width without risking that the components of the header would overlap and render it unusable. Since we allow the header to be customized to whether or not it contains a search, login, and/or 1-2 action buttons, I haven't been able to figure out a way to work it in the FOUC so that it's usable AND has no jitter.
