### ISSUE TITLE
Mobile browsers not aggregating tabs

### ISSUE THREAD

**Issue by markwelker** [byuweb/byu-theme-components#461]
# Description
Mobile browsers do not display menu with aggregated tabs, desktop Chrome's mobile device toolbar displays as it should, this only appears on actual mobile devices. I've only personally tested on android devices.

![screenshot](https://user-images.githubusercontent.com/35548890/62718309-d29fe900-b9c2-11e9-8971-49afd12ff4bf.png)

# Websites Affected

ge.byu.edu
honors.byu.edu
etc.

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [x] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [x] Chrome for Android
- [x] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [x] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by ThatJoeMoore** [comment]
I'm unable to reproduce on Android in either Chrome or Firefox (latest versions), but I think I know what the proximal issue is, though I don't know the root issue. @markwelker, Could you tell us what version of Android and of Chrome you are running?

It looks to me like there was an issue loading or executing the JavaScript bundle, so you got stuck with the Flash of Unstyled Content styles. Without having access to the browser's logs, I can't know what that root cause is. We can, however, make it fail more gracefully.

In the past, we made sure that the FOUC styles (which normally display only for the split-second before the theme JavaScript executes) also functioned as fallback styles, in case the JS load went poorly. That meant that we had a slightly jankier experience on mobile, as there's no good way to emulate the expanding menu with pure CSS, but it was worth it to have the page be progressively enhanced. We should probably restore that, and we can talk about the best way to do so visually. I may be able to take a pass at that early next week, especially now that my effort to shrink the JS bundle is wrapping up.

**Comment by markwelker** [comment]
Thanks @ThatJoeMoore 
Android 8.1.0 
Mobile Chrome v76.0.x latest
Mobile Firefox v68.0 latest

I also tested on a Android 9 borrowed, but I don't have specs on that.

I just pulled it up again while connected to computer and it looks like it displays the menu just fine now.

**Comment by markwelker** [comment]
![Uploading screenshot-2.png…]()
screenshot attached.

I can't replicate the bug now, though I replicated it several times across multiple devices yesterday.

Perhaps it's closing time for this issue, thanks for your time.
